apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: webapps
  name: app-rolebinding
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: webapps
roleRef:
  kind: Role
  name: app-role
  apiGroup: rbac.authorization.k8s.io
