apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: webapps
  name: app-role
rules:
- apiGroups:
  - ""
  - "apps"
  - "autoscaling"
  - "batch"
  - "extensions"
  - "policy"
  - "rabc.authorization.k8s.io"
  resources:
  - "pods"
  - "componentstatuses"
  - "configmaps"
  - "daemonsets"
  - "deployments"
  - "events"
  - "endpoints"
  - "horizonatalpodautoscalers"
  - "ingress"
  - "jobs"
  - "limitranges"
  - "namespaces"
  - "nodes"
  - "pods"
  - "persistentvolumes"
  - "persistentvolumeclaims"
  - "resourcequotas"
  - "replicasets"
  - "replicationcontrollers"
  - "serviceaccounts"
  - "services"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "create"
  - "update"
  - "patch"
  - "delete"
